[package]
name = "user_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
riscv = { git = "https://github.com/rcore-os/riscv", features = ["inline-asm"] } 
sbi-rt = { version = "0.0.2", features = ["legacy"] }


[profile.release]
debug = true

# [features]
# board_qemu = []
# board_k210 = []